### ISSUE TITLE
Support reassembly of fragmented traffic

### ISSUE THREAD

**Issue by jfallows** [kaazing/nuklei#6]
When higher level protocol traffic is fragmented over different TCP segments, a receiving nukleus sees the data fragmented over non-contiguous memory and therefore cannot apply a flyweight directly.

Even though fragmentation and reassembly is a common issue across different higher level protocols, only the specific higher level protocol understands where its frame boundaries are located, so this issue cannot be solved entirely generically in the nuklei core.

However, we could provide a reusable traffic reassembler that can be informed of the higher level protocol boundaries at the receiving side, and guarantee that reassembled data received by a nukleus is higher level protocol frame aligned, even if multiple higher level protocol frames are received in a single contiguous block of memory.

**Comment by cmebarrow** [comment]
Does AlignedMikro deal with this?

**Comment by jfallows** [comment]
Yes, although the current design deserves some further review.

The implementation in place at the moment is sufficient to support automated external network testing of AMQP (eg. via K3PO) even if that introduces unpredictable fragmentation.

The internal Nuklei API that exposes this functionality probably needs some further simplification as we work through the different use cases.

For example, we need to handle both fixed length protocols (eg. AMQP) and variable length protocols (eg. HTTP).
